### ISSUE TITLE
Unable to launch/attach Firefox at all on OSX.

### ISSUE THREAD

**Issue by JimmyDeemo** [firefox-devtools/vscode-firefox-debug#178] opened 2020-01-29 15:14 UTC
I'm trying to go through the Heaps.io 'hello world' introduction but use Firefox as my browser and I cannot get VSCode to launch Firefox or attach, despite playing with the settings.

When I try and debug, VSCode just waits for something to happen and then doesn't load Firefox. I have tried launching the browser via the command line and attaching (using -start-debugger-server) but no luck their either. I have set the debug config options in the browser settings too.

The launch config file is the default one as follows;
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch index.html",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "file": "${workspaceFolder}/index.html"
        },
        {
            "name": "Launch localhost",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "url": "http://localhost/index.html",
            "webRoot": "${workspaceFolder}"
        },
        {
            "name": "Attach",
            "type": "firefox",
            "request": "attach"
        },
        {
            "name": "Launch WebExtension",
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "addonPath": "${workspaceFolder}"
        }
    ]
}
```

VSCode Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0

MacOS Version: 10.15.2 (19C57)

Please can someone help me diagnose where the problem lies as i'm unsure of whether it is VSCode, Firefox or the plugin that is causing the issue.

**Comment by hbenl** [comment] 2020-01-30 19:35
I'll have a look at this next week when I have access to a Mac.

**Comment by JimmyDeemo** [comment] 2020-01-30 20:30
Thank you. Similar issue here from a few months ago; https://stackoverflow.com/questions/57261472/firefox-does-not-open-when-debugging-in-visual-studio-code.

**Comment by JimmyDeemo** [comment] 2020-02-15 10:35
@hbenl Any update on this please?

**Comment by hbenl** [comment] 2020-02-17 18:41
I think I have found out what's happening: at the end of a debugging session, the debug adapter first tries to stop Firefox by closing all of its tabs (and hence the Firefox window). On Windows and Linux, Firefox shuts itself down after that, but on the Mac it doesn't: the Firefox process keeps running (with no window) and blocks the debugger port. The debug adapter waits for a second and if the Firefox process is still running, it kills the process. This worked in the past but now it seems that VS Code kills the debug adapter process while that process is waiting for Firefox to shut down, so the debug adapter never gets a chance to kill Firefox.
To verify this please have a look if you can see the Firefox icon in the dock _with a small black dot at the bottom_. The dot indicates that Firefox is running (even if it has no window open). If you can see that small black dot, try to stop Firefox using the context menu from the dock and then try to start another debug session, now it should work.
Please tell me if this is what's happening in your case. I will change the debug adapter to kill Firefox immediately at the end of a debug session on the Mac - I tried to avoid this in the past because killing Firefox can lead to a broken profile when you use the `keepProfileChanges` option...

**Comment by JimmyDeemo** [comment] 2020-02-17 19:52
Thanks for the response @hbenl but i'm afriad this doesn't seem like the case. I am not getting any reaction out of VSCode to launch Firefox at all, let alone a second time. My test case involves calling 'Quit' from the docker before trying to launch the debug session but it's almost as if VSCode doesn't seem to know where Firefox is installed in order to launch the process. I would also note that Firefox isn't killed should it be running and my debug session is ended. I literally cannot get any response from the App at all; with Chrome it seems to work instantly.

Perhaps you could share a test project or a sample launch file?

**Comment by hbenl** [comment] 2020-02-17 20:19
> it's almost as if VSCode doesn't seem to know where Firefox is installed in order to launch the process

if that was the case then the debug adapter would show an error message that it can't find Firefox...

> Perhaps you could share a test project or a sample launch file?

your launch file is correct and the content of the project doesn't make any difference until Firefox is started and the debugger is attached...

Here's some more things you could try:
* try setting `reAttach` to `false` in your launch configuration - that changes how Firefox is launched
* try setting `port` to a different value (the default is 6000) - perhaps something is occupying that port
* try setting `firefoxExecutable` to the path of the Firefox executable (i.e. the path you enter on the command line to start Firefox) - I don't think that's the reason but it's worth trying

**Comment by hbenl** [comment] 2020-02-17 20:24
Do you perhaps have an X11 server installed and running? That could occupy port 6000...

**Comment by JimmyDeemo** [comment] 2020-02-18 21:58
Thanks for the suggestions @hbenl it looks as if `reAttach` was the issue; I am now able to get Firefox to launch when I start debugging. :D

However, right now I am unable to hit breakpoints. Could this be due to another configuration issue? Once again, regarding this part, Chrome seems to function out of the box and breaks in the .hx file at the selected location.

**Comment by hbenl** [comment] 2020-02-23 19:31
Did you also try the `port` option? If that option is the root cause, it would make sense that Firefox is launched when setting `reAttach` to `false`, but debugging would still not work (because VS Code couldn't connect to the Firefox debugger).
Also, do the breakpoints remain gray after launching Firefox (and until the debug session is stopped)? And what is a .hx file? Can you point me to a sample project that uses that kind of file?

**Comment by JimmyDeemo** [comment] 2020-03-03 20:18
Sorry for my lack of response on this; I haven't had the time to dig further. I will endeavour to check the port setting, to see if that would have any effect.

Re: sample project, i'm following the 'hello world' example over at the Heaps website here; https://heaps.io/documentation/hello-world.html. Only switching the parts about Chrome to use Firefox instead.

**Comment by phepranto** [comment] 2020-03-30 23:06
I'm running into the same exact problem on my really fresh Windows 10 installation (per chance also while doing the same tutorial). I dont think there's any software installed that could possibly block any debugging port.

Changing reAttach to false did fix firefox not opening at all but now it's ignoring breakpoints.

**Comment by hbenl** [comment] 2020-04-05 17:13
@phepranto Thanks a lot, so it was the `port` option after all!

**Closed by hbenl** 2020-04-05 17:13 UTC
Labels: needs more info

**Comment by JimmyDeemo** [comment] 2020-04-08 19:11
Thanks for the update @phepranto, I can confirm that the above configuration allows me to debug in a stand alone Firefox.

**Comment by ibilon** [comment] 2020-04-26 18:28
I just encountered that same issue as well, is there a way the extension could warn if the port is already in use? Or is that because it assumes that the open port is a previously opened firefox debug?

**Comment by hbenl** [comment] 2020-05-07 18:15
> Or is that because it assumes that the open port is a previously opened firefox debug?

That is exactly the issue here and I don't know how to (reliably) determine if the port was opened by Firefox or some other application.
