### ISSUE TITLE
Attaching to firefox dev server does not work

### ISSUE THREAD

**Issue by matthias-eb** [firefox-devtools/vscode-firefox-debug#359] opened 2024-03-16 14:10 UTC
My configuration: 
```json
{
      "name": "Run after build",
      "type": "firefox",
      "request": "launch",
      "file": "${workspaceFolder}/dist/index.html"
    }
```
Starting this configuration successfully starts the firefox dev server. But it then fails to attach as the firefox dev server is started on `127.0.0.1:6000` and the vscode extension tries to connect to `::1:6000`. I do not see a solution to either let the browser or the extension use another host.

**Comment by matthias-eb** [comment] 2024-03-16 14:15
Some further information: 
OS: Arch Linux (Garuda Linux)
VSCode: code-oss
command to check on which port the application listens: `sudo lsof -i -P -n | grep LISTEN`

**Comment by hbenl** [comment] 2024-03-18 13:22
When you say "VSCode: code-oss" does that mean you're using VSCodium? In that case this would be a duplicate of #253 .

**Closed** 2024-03-18 13:42 UTC
