### ISSUE TITLE
Breakpoints stop working on Create React App dev server after editing the code and the page reloads

### ISSUE THREAD

**Issue by synchronos-t** [firefox-devtools/vscode-firefox-debug#103] opened 2019-04-11 12:24 UTC
On Create React App/react-scripts development server, the breakpoints work normally at first. But then if I edit the code and push save and the dev server automatically reloads the page, the breakpoints stop working. They still seem to break the execution, but they don't become active in VSCode (or Firefox, either), and I cannot use the Continue button to continue the execution. Restarting VSCode or Firefox doesn't work, either. Only after I restart the development server, they start working again.

The log.fileLevel.default at "Error" doesn't give anything. When set to "Debug", I can't spot anything that would indicate anything not working properly.

**Comment by hbenl** [comment] 2019-04-14 18:50
I think this was also caused by the bugs that I fixed in version 1.7.11 - please tell me if it's fixed now.

**Comment by digitarald** [comment] 2019-08-29 21:30
@synchronos-t just checking if you had a chance to verify that this is fixed. Thank you.

**Comment by synchronos-t** [comment] 2019-08-30 08:23
Ach, yes, sorry, forgot that. It indeed started working after that update, thanks! The breakpoints have been working after that, at least generally. Sometimes, however, they seem to stop working (in the same way, i.e. they stop the execution, but don't show the line in the editor) and refreshing the page and/or reconnecting the debugger doesn't help, only rebooting the development server gets them working again. But I don't have anything solid to open an issue about that, at least not yet.

**Closed** 2019-08-30 08:23 UTC
Labels: needs more info
