### ISSUE TITLE
Add support for Remote - SSH

### ISSUE THREAD

**Issue by MakoPhil** [firefox-devtools/vscode-firefox-debug#104] opened 2019-05-06 01:19 UTC
Firstly I want to thank you for your efforts so far!

As I'm sure you're aware, Microsoft have added support to VS Code for remote development on containers, by SSH, and through WSL. I'm particularly interested in the SSH solution.

https://code.visualstudio.com/docs/remote/ssh

Unfortunately I can't get the Firefox Debug addon to work with this setup. Here's what I've tried:

- Mapped port 5001 (Angular web app port) local to remote when connecting by SSH
- Install addon both remotely and locally (it defaults to remote but can be [forced to local](https://code.visualstudio.com/docs/remote/ssh#_advanced-forcing-an-extension-to-run-locally-remotely) - I'm not sure which is correct but my guess is it should be local)

The browser never launches with any of these combinations, although I can see the debug adapter spinning up locally when installed on local, and remotely when installed on remote. Here is my `launch.json` entry:

    {
        "name": "Attach to Firefox",
        "type": "firefox",
        "request": "launch",
        "reAttach": true,
        "url": "https://127.0.0.1:5001/",
        "webRoot": "${workspaceFolder}/App/ClientApp/dist/",
        "profileDir": "${workspaceFolder}/.vscode/firefox_debug_profile",
        "keepProfileChanges": true,
        "skipFiles": [
            "${workspaceFolder}/App/ClientApp/node_modules/**",
            "${workspaceFolder}/App/ClientApp/dist/**",
            "http?(s):/**"
        ],
        "pathMappings": [
            {
                "url": "webpack:///",
                "path": "${workspaceFolder}/App/ClientApp/"
            },
            {
                "url": "ng:///",
                "path": "${workspaceFolder}/App/ClientApp/src/"
            }
        ],
        "showConsoleCallLocation": true
    }

I have also tried Attach mode with addon installed locally; VS Code connects, but breakpoints don't hit.

**Comment by hbenl** [comment] 2019-05-07 18:41
> my guess is it should be local

correct - the extension needs to launch Firefox _locally_ (not on the remote machine)

> The browser never launches with any of these combinations

That's odd - perhaps the extension was installed in _both_ locations and VS Code then decided to use the remote one? Try to uninstall the remote version.

> VS Code connects, but breakpoints don't hit.

That sounds like the `pathMappings` may be wrong - do the breakpoints remain grey after attaching? If so, try to remove the `pathMappings` from your configuration and redefine them using the Loaded Scripts Explorer.

**Comment by MakoPhil** [comment] 2019-05-08 07:16
I did have the extension installed both locally and remotely, but VS Code is clever enough to only enable one at a time. Uninstalling, rather than just disabling the extension on the remote host made no difference.
The plot thickens... I tried launching the Firefox debugger against a local project (that is, no remote SSH connection at all), and all I got was the Mozilla Crash Reporter (unfortunately the Details button is disabled so that's all the information I can give you).
This could be a problem with VS Code Insiders, because it works fine on the same project with regular VS Code.

**Comment by hbenl** [comment] 2019-05-09 17:08
I can't reproduce the problem with launching Firefox, but I see that breakpoints don't work and it looks like this can't be fixed by configuration alone, I'll have to add support for remote workspaces to this extension.

**Comment by MakoPhil** [comment] 2019-05-09 22:39
Thanks for looking in to this. I should add that I'm running on Pop!_OS, a derivative of Ubuntu.
Also I found that if I take out the settings for `profileDir` and `keepProfileChanges`, I get the crash report dialog as well, maybe Firefox is silently crashing otherwise?

**Comment by jonfen** [comment] 2019-08-29 21:43
Besides SSH, devcontainer support is now a big one given their WSL2.0 development push.

https://code.visualstudio.com/docs/remote/containers
https://code.visualstudio.com/docs/remote/containers#_devcontainerjson-reference

**Comment by Chuxel** [comment] 2019-08-29 21:49
The [extension guide](https://code.visualstudio.com/api/advanced-topics/remote-extensions) for VS Code Remote provides additional details on the architecture for Remote - SSH, containers, and WSL extensions. You will not see this locally.

The Debugger for Chrome extension has been modified to work in this environment as a reference implementation: 
https://github.com/Microsoft/vscode-chrome-debug

**Closed** 2019-09-10 18:31 UTC
Labels: enhancement

**Comment by hbenl** [comment] 2019-09-10 19:13
Version 2.2.0 of the debug adapter supports remote development. Please try it out and tell me if it works for you.

**Comment by jonfen** [comment] 2019-10-31 21:04
> Version 2.2.0 of the debug adapter supports remote development. Please try it out and tell me if it works for you.

![image](https://user-images.githubusercontent.com/56961/67985822-4bdc6000-fbef-11e9-9446-cbd975fecf0c.png)

@hbenl I get the following error trying to follow the instructions you have for https://github.com/firefox-devtools/vscode-firefox-debug#attach

The vscode instance is running in a .devcontainer, while the firefox browser (`firefox -start-debugger-server http://localhost:5000`) is running on the host (my laptop).
