### ISSUE TITLE
Doesn't find executable in default location

### ISSUE THREAD

**Issue by Regenhardt** [firefox-devtools/vscode-firefox-debug#138] opened 2019-10-08 08:15 UTC
I have the standard Firefox 64bit installation, into C:\Program Files\Mozilla Firefox, but it always says executable not found. Any idea why?

**Comment by hbenl** [comment] 2019-10-10 17:12
No idea, it does look for a file `C:\Program Files\Mozilla Firefox\firefox.exe`...
Do you maybe have `firefoxExecutable` set in your `launch.json` or in your VS Code workspace or user settings?

**Comment by Regenhardt** [comment] 2019-10-10 18:47
So here's something strange: 
The option was actually set to "C:\Program Files\Mozilla Firefox\firefox.exe", but then I removed it and now it works. Not sure why. Thanks for the help, didn't think about looking there since I just tried it for the first time!

**Comment by hbenl** [comment] 2019-10-11 13:29
Perhaps the path wasn't properly escaped? It would need to be set like this:
```
"firefoxExecutable": "C:\\Program Files\\Mozilla Firefox\\firefox.exe"
```

**Comment by Regenhardt** [comment] 2019-10-13 13:40
I actually looked at the settings GUI, does it have to be escaped there too? That would totally explain why it didn't work.

**Comment by hbenl** [comment] 2019-10-14 18:34
> I actually looked at the settings GUI, does it have to be escaped there too?

No, in the settings GUI you enter the values unescaped, so the only explanation I can think of now is that there was a typo in that setting...

@digitarald Yes, in the source code it needs to be escaped, of course. The question is if the user needs to escape it if he enters the path (and the answer is yes if he enters it into a json file).

**Comment by hbenl** [comment] 2019-10-18 19:17
Closing this as the issue is resolved (even though we didn't find the root cause).

**Closed by hbenl** 2019-10-18 19:17 UTC
